apiVersion: apps/v1
kind: Deployment
metadata:
  name: wifi-ap
  labels:
    infra: ap
spec:
  replicas: 1
  selector:
    matchLabels:
      infra: ap
  template:
    metadata:
      labels:
        infra: ap
    spec:
      hostNetwork: true
      containers:
      - name: wifi-ap
        image: ghcr.io/scholzj/kafka-at-the-edge-wifi-ap:latest
        securityContext:
          privileged: true # otherwise hostapd can't change channels for some reason
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
