apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sensor-data-aggregated
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    #cleanup.policy: compact
    retention.ms: 604800000
    segment.bytes: 107374182
    min.insync.replicas: 2
