apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: frontend
  namespace: prometheus
  labels:
    app: frontend
    prometheus: prometheus
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames:
      - myproject
  podMetricsEndpoints:
  - path: /q/metrics
    port: http